apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-your-name-app-backend
  namespace: your-name-namespace
data:
  # DATABASE
  DATABASE_URL: "db-host.example.internal:6433;databaseName=APP_DATABASE;instanceName=instance;encrypt=false"
  DATABASE_USER: "db_user"
  DATABASE_PASSWORD: "db_password"

  # DNIC / External Service
  DNIC_ORGANIZATION: "ORG_NAME"
  DNIC_ORGANIZATION_PASSWORD: "org_password"