apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-your-name-app-backend
  namespace: your-name-namespace
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  tls:
  - hosts:
    - your-name-app-backend.int.example.com
    secretName: wildcard-tls
  rules:
  - host: your-name-app-backend.int.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: your-name-app-backend
            port:
              number: 8080
