apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: your-name-app
  namespace: integra-your-name-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  tls:
    - hosts:
        - your-name-app-int.example.com
      secretName: wildcard-tls
  rules:
    - host: your-name-app-int.example.com
      http:
        paths:
          # Backend
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: your-name-app-backend
                port:
                  number: 8080
          # Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: your-name-app-frontend
                port:
                  number: 80