apiVersion: v1
kind: Service
metadata:
  name: your-name-app-frontend
  namespace: integra-your-name-app
spec:
  selector:
    app: your-name-app-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP